package screens;

public enum ViewState {

    DECK_SCREEN,
    QUIZ_MENU,
    START_QUIZ,
    SHOW_PROBLEM,
    SHOW_ANSWER,
    DECK_CREATED,
    DECK_DELETED,
    DECK_IMPORTED,
    CARD_CREATED,
    CARD_DELETED,
    CARD_MOVED,
    QUIZ_CREATED,
    QUIZ_DELETED,
    CARD_EDITED,
    DECK_EDITED,
    QUIZ_EDITED
}
